#!/bin/bash
echo "NO"
java -cp ../bin Main server load "../inputs/NorthEmissionsOpponent.in" < no | java -cp ../bin Main > no
echo "SO"
java -cp ../bin Main server load "../inputs/SouthEmissionsOpponent.in" < so | java -cp ../bin Main > so
echo "EO"
java -cp ../bin Main server load "../inputs/EastEmissionsOpponent.in" < eo | java -cp ../bin Main > eo
echo "WO"
java -cp ../bin Main server load "../inputs/WestEmissionsOpponent.in" < wo | java -cp ../bin Main > wo
echo "PO"
java -cp ../bin Main server load "../inputs/ParadiseEmissionsOpponent.in" < po | java -cp ../bin Main > po
